import Header from "@/components/shared/Header";
import { Metadata } from "next";
import RightSidebar from "@/components/shared/RightSideBar"
import { Home, Settings, LogOut } from 'lucide-react';

const items = [
  { label: 'Home', icon: <Home className='h-5 w-5' /> },
  { label: 'Settings', icon: <Settings className='h-5 w-5' /> },
  { label: 'Logout', icon: <LogOut className='h-5 w-5' />  },
];

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>
        <Header />
          <RightSidebar items={items} />
          {children}</body>
      </html>
    );
  }